const details = require('../model/details')
function detailss(req,res){
    details.create({
      img:'/images/details/01.jpg',
      price:'￥399',
      oldprice:'￥1799',
      zhekou:'2.2折',
      list:[{
         img:'/images/details/02.jpg',
      },{
         img:'/images/details/03.jpg',
      },{
         img:'/images/details/04.jpg',
      },{
         img:'/images/details/05.jpg',
      },{
         img:'/images/details/06.jpg',
      }],
      list1:[{
         yanse1:'奶油白',
         image:'/images/details/xiaotu1.jpg',
      },{
         yanse1:'杏色',
         image:'/images/details/xiaotu1.jpg',
      },{
         yanse1:'红色',
         image:'/images/details/01.jpg',
      }],
      list2:[{
         size:'S'
      },{
         size:'L'
      },{
         size:'M'
      },{
         size:'XL'
      }]
    })

     res.end('123')
}
module.exports = detailss
/**
 * 
 * 
 * {data:[{
        img:'/images/details/01.jpg',
        price:'￥399',
        oldprice:'￥1799',
        zhekou:'2.2折',
        list:[{
           img:'/images/details/02.jpg',
        },{
           img:'/images/details/03.jpg',
        },{
           img:'/images/details/04.jpg',
        },{
           img:'/images/details/05.jpg',
        },{
           img:'/images/details/06.jpg',
        }],
        list1:[{
           yanse:'奶油白',
           image:'/images/details/xiaotu1.jpg',
        },{
           yanse:'杏色',
           image:'/images/details/xiaotu1.jpg',
        },{
           yanse:'红色',
           image:'/images/details/01.jpg',
        }],
        list2:[{
           size:'S'
        },{
           size:'L'
        },{
           size:'M'
        },{
           size:'XL'
        }]
     }]}
 */