const shop=require('../model/Shop')
function showshop(req,res){
    shop.create({
        data:[{
            img:"/images/lastcrazy/sx1.webp",
            fengding:'到手价三折封顶',
                list:[{
                        img1:"/images/lastcrazy/sx2-1(1).webp",
                        dazhe:"2.2折",
                        money:"￥224",
                        yuanjia:"￥998"
                    },{
                        img1:"/images/lastcrazy/sx2-1(2).webp",
                        dazhe:"1.7折",
                        money:"￥299",
                        yuanjia:"￥1780"
                    },{
                        img1:"/images/lastcrazy/sx2-1(3).webp",
                        dazhe:"1.7折",
                        money:"￥99",
                        yuanjia:"￥598"
                    }],
            shop:"百斯盾男女装-最后疯抢专场",
            daojishi:"01"  
        },{
            img:"/images/lastcrazy/sx2.webp",
            fengding:'到手价三折封顶',
                list:[{
                        img1:"/images/lastcrazy/sx2-2(1).webp",
                        dazhe:"2.2折",
                        money:"￥224",
                        yuanjia:"￥998"
                    },{
                        img1:"/images/lastcrazy/sx2-2(2).webp",
                        dazhe:"1.7折",
                        money:"￥299",
                        yuanjia:"￥1780"
                    },{
                        img1:"/images/lastcrazy/sx2-2(3).webp",
                        dazhe:"1.7折",
                        money:"￥99",
                        yuanjia:"￥598"
                    }],
            shop:"乔伊思-女装最后疯抢专场",
            daojishi:"01"  
        },{
            img:"/images/lastcrazy/sx3.webp",
            fengding:'到手价三折封顶',
                list:[{
                        img1:"/images/lastcrazy/sx3-3(1).webp",
                        dazhe:"2.2折",
                        money:"￥224",
                        yuanjia:"￥998"
                    },{
                        img1:"/images/lastcrazy/sx3-3(2).webp",
                        dazhe:"1.7折",
                        money:"￥299",
                        yuanjia:"￥1780"
                    },{
                        img1:"/images/lastcrazy/sx3-3(3).webp",
                        dazhe:"1.7折",
                        money:"￥99",
                        yuanjia:"￥598"
                    }],
            shop:"鲨鱼VISHARK鞋包-最后疯抢专场",
            daojishi:"01"  
        },{
            img:"/images/lastcrazy/sx4.webp",
            fengding:'到手价三折封顶',
                list:[{
                        img1:"/images/lastcrazy/sx4-4(1).webp",
                        dazhe:"2.2折",
                        money:"￥224",
                        yuanjia:"￥998"
                    },{
                        img1:"/images/lastcrazy/sx4-4(2).webp",
                        dazhe:"1.7折",
                        money:"￥299",
                        yuanjia:"￥1780"
                    },{
                        img1:"/images/lastcrazy/sx4-4(3).webp",
                        dazhe:"1.7折",
                        money:"￥99",
                        yuanjia:"￥598"
                    }],
            shop:"三枪内衣-最后疯抢",
            daojishi:"01"  
        },{
            img:"/images/lastcrazy/sx5.webp",
            fengding:'到手价三折封顶',
                list:[{
                        img1:"/images/lastcrazy/sx5-5(1).webp",
                        dazhe:"2.2折",
                        money:"￥224",
                        yuanjia:"￥998"
                    },{
                        img1:"/images/lastcrazy/sx5-5(2).webp",
                        dazhe:"1.7折",
                        money:"￥299",
                        yuanjia:"￥1780"
                    },{
                        img1:"/images/lastcrazy/sx5-5(3).webp",
                        dazhe:"1.7折",
                        money:"￥99",
                        yuanjia:"￥598"
                    }],
            shop:"裂帛女装专场",
            daojishi:"01"  
        },{
            img:"/images/lastcrazy/sx6.webp",
            fengding:'到手价三折封顶',
                list:[{
                        img1:"/images/lastcrazy/sx6-6(1).webp",
                        dazhe:"2.2折",
                        money:"￥224",
                        yuanjia:"￥998"
                    },{
                        img1:"/images/lastcrazy/sx6-6(2).webp",
                        dazhe:"1.7折",
                        money:"￥299",
                        yuanjia:"￥1780"
                    },{
                        img1:"/images/lastcrazy/sx6-6(3).webp",
                        dazhe:"1.7折",
                        money:"￥99",
                        yuanjia:"￥598"
                    }],
            shop:"卡帝乐鳄鱼女装-最后疯抢专场",
            daojishi:"01"  
        },{
            img:"/images/lastcrazy/sx7.webp",
            fengding:'到手价三折封顶',
                list:[{
                        img1:"/images/lastcrazy/sx7-7(1).webp",
                        dazhe:"2.2折",
                        money:"￥224",
                        yuanjia:"￥998"
                    },{
                        img1:"/images/lastcrazy/sx7-7(2).webp",
                        dazhe:"1.7折",
                        money:"￥299",
                        yuanjia:"￥1780"
                    },{
                        img1:"/images/lastcrazy/sx7-7(3).webp",
                        dazhe:"1.7折",
                        money:"￥99",
                        yuanjia:"￥598"
                    }],
            shop:"大嘴猴paul frank-最后疯抢专场",
            daojishi:"01"  
        }],
        // 下期预告
    yugao:[{
        img:"/images/lastcrazy/yg-1(1).webp",
    },{
        img:"/images/lastcrazy/yg-1(2).webp",
    },{
        img:"/images/lastcrazy/yg-1(3).webp",
    },{
        img:"/images/lastcrazy/yg-1(4).webp",
    },{
        img:"/images/lastcrazy/yg-1(5).webp",
    },{
        img:"/images/lastcrazy/yg-1(6).webp",
    },{
        img:"/images/lastcrazy/yg-1(7).webp",
    },{
        img:"/images/lastcrazy/yg-1(7).webp",
    }]
    })
    res.end('1223')
}
module.exports = showshop