function showhomeapp(req,res){
    res.render('homeapp',{
    //唯品快抢 
     homeappnav:[{
         src1:"/images/homeapp/19.jpg",
         src2:"/images/homeapp/20(1).png",
         logoprice:"99"
     },{
        src1:"/images/homeapp/20.jpg",
        src2:"/images/homeapp/20(4).png",
        logoprice:"129"
    },{
        src1:"/images/homeapp/21.jpg",
        src2:"/images/homeapp/20(3).png",
        logoprice:"99"
    },{
        src1:"/images/homeapp/22.webp",
        src2:"/images/homeapp/20(1).png",
        logoprice:"119"
    }],
    // 精选店铺
    specificshop:[{
        img:"/images/homeapp/27.jpg",
        name:'荣耀数码电子精选专场',
        price:"4.9"
    },{
        img:"/images/homeapp/28.jpg",
        name:'HYUNDAI厨房电器好货超值购',
        price:"5"
    },{
        img:"/images/homeapp/29.jpg",
        name:'audio-technica耳机品质专场',
        price:"3.8"
    },{
        img:"/images/homeapp/30.jpg",
        name:'东菱厨房电器精选专场',
        price:"4.3"
    }],
    // 精选爆款
    sectionlisthot:[{
        hotlistimg:"/images/homeapp/32(1).jpg",
        hotlistdesc:"电水壶/热水瓶"
    },{
        hotlistimg:"/images/homeapp/32(2).jpg",
        hotlistdesc:"挂烫机"
    },{
        hotlistimg:"/images/homeapp/32(3).jpg",
        hotlistdesc:"吸尘器"
    },{
        hotlistimg:"/images/homeapp/32(4).jpg",
        hotlistdesc:"养生壶"
    },{
        hotlistimg:"/images/homeapp/32(5).jpg",
        hotlistdesc:"电吹风"
    },{
        hotlistimg:"/images/homeapp/32(6).jpg",
        hotlistdesc:"绞肉机"
    },{
        hotlistimg:"/images/homeapp/32(7).jpg",
        hotlistdesc:"电压力锅"
    },{
        hotlistimg:"/images/homeapp/32(8).jpg",
        hotlistdesc:"电饼铛烤饼机"
    }]
    })
}
module.exports = showhomeapp
