function showLife(req,res){
    res.render('life',{
        data:[{
            img:"/images/life/tu1.jpg",
            goodsname:'金秋蟹礼  团员佳肴',
            price1:'1.2折起',
            price2:'剩两天'
        },{
            img:"/images/life/tu2.jpg",
            goodsname:'舌尖上的食品材料-最后疯抢专场',
            price1:'1.2折起',
            price2:'剩两天'
        },{
            img:"/images/life/tu3.jpg",
            goodsname:'唯品会海外直采美酒-最后疯抢专场',
            price1:'2折封顶|全场折上4折起',
            price2:'剩两天'
        },{
            img:"/images/life/tu4.jpg",
            goodsname:'百草味休闲零食专场',
            price1:'1.4折起',
        },{
            img:"/images/life/tu5.jpg",
            goodsname:'海底捞HI食品特卖专场',
            price1:'1.5折起',
        },{
            img:"/images/life/tu6.jpg",
            goodsname:'澳洲Swisse保养护肤折扣专场',
            price1:'5折封顶', 
        },{
            img:"/images/life/tu7.jpg",
            goodsname:'修正营养保健精选专场',
            price1:'4折封顶',
        },{
            img:"/images/life/tu8.jpg",
            goodsname:'郎白酒好货超值购',
            price1:'4.9折封顶',
        },{
            img:"/images/life/tu9.jpg",
            goodsname:'五谷磨房茗茶调精选专场',
            price1:'1.9折起',
        },{
            img:"/images/life/tu10.jpg",
            goodsname:'参之源传统滋补格调专场',
            price1:'5折封顶',
        }]
    })
}
module.exports = showLife