function shownewbeauty(req,res){
     res.render('newbeauty',{
     sectionlisttype:[{
     src:'/images/newbeauty/3(1).jpg',
     num:"1"
     },{
     src:'/images/newbeauty/3(2).jpg',
     num:"2"
     },{
     src:'/images/newbeauty/3(3).gif',
     num:"3"
     },{
     src:'/images/newbeauty/3(4).jpg',
     num:"4"
     },{
     src:'/images/newbeauty/3(5).jpg',
     num:"5"
     },{
     src:'/images/newbeauty/3(6).gif',
     num:"6"
     },{
     src:'/images/newbeauty/3(7).jpg',
     num:"7"
     },{
     src:'/images/newbeauty/3(8).jpg',
     num:"8"
     },{
     src:'/images/newbeauty/3(9).jpg',
     num:"9"
     },{
     src:'/images/newbeauty/3(10).jpg',
     num:"10"
     }],
     //唯品快抢 
     homeappnav:[{
          src1:"/images/newbeauty/4(1).jpg",
          src2:"/images/newbeauty/5(1).png",
          logoprice:"58"
      },{
         src1:"/images/newbeauty/4(2).jpg",
         src2:"/images/newbeauty/5(2).png",
         logoprice:"89"
     },{
         src1:"/images/newbeauty/4(3).jpg",
         src2:"/images/newbeauty/5(3).png",
         logoprice:"49"
     },{
         src1:"/images/newbeauty/4(4).jpg",
         src2:"/images/newbeauty/5(1).png",
         logoprice:"25"
     }]
     })
}
module.exports=shownewbeauty

